trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift cluster'
    version: '4.2'
    cmd: 'oc project myapp'
  displayName: Switch to myapp project
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift cluster'
    version: '4.2'
    cmd: 'oc new-app https://github.com/rkepp/QuarkusLabs'
    ignoreFlag: true
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift cluster'
    version: '4.2'
    cmd: 'oc expose svc QuarkusLabs'
    ignoreFlag: true
  displayName: Create route
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift cluster'
    version: '4.2'
    cmd: 'oc start-build QuarkusLabs --follow'
  displayName: Start new build
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift cluster'
    version: '4.2'
    cmd: 'oc status'